# Generated by Django 6.0 on 2026-04-21 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('games_library_categorization', models.CharField(blank=True, choices=[('', ''), ('R', 'Règles'), ('E', 'Exercice'), ('S', 'Symbolique'), ('A', 'Assemblage')], max_length=1)),
                ('adapted_games_library_categorization_1', models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('exp', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('exp', 'expérimentation'), ('fab', 'fabrication')], max_length=10)),
                ('adapted_games_library_categorization_2', models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('exp', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('exp', 'expérimentation'), ('fab', 'fabrication')], max_length=10)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('players_number', models.CharField(blank=True, max_length=10)),
                ('details', models.TextField(blank=True)),
                ('entry_year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2013)])),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Number')),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('myludo_path', models.CharField(blank=True, max_length=200, null=True)),
                ('cards_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cards_size', models.CharField(blank=True, max_length=40)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcode')),
                ('image', models.ImageField(blank=True, upload_to='games_images')),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('game_type', models.CharField(choices=[('boardgame', 'jds'), ('rpg', 'jdr'), ('wooden', 'bois'), ('toys', 'jouet')], default='boardgame', max_length=20)),
                ('last_inventory_date', models.DateField(blank=True, null=True, verbose_name='last inventory date')),
                ('rules_video_link', models.CharField(blank=True, max_length=100, null=True)),
                ('for_child', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False)),
                ('missing_items', models.TextField(blank=True, null=True)),
                ('inventory', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(blank=True, to='games.author')),
                ('editors', models.ManyToManyField(blank=True, to='games.editor')),
                ('illustrators', models.ManyToManyField(blank=True, to='games.illustrator')),
                ('labels', models.ManyToManyField(blank=True, to='games.label')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.location')),
                ('mechanisms', models.ManyToManyField(blank=True, to='games.mechanism')),
                ('themes', models.ManyToManyField(blank=True, to='games.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
