# Generated by Django 6.0 on 2026-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(default='À renseigner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='adapted_games_library_categorization_1',
            field=models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('expr', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('expé', 'expérimentation'), ('fab', 'fabrication')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='adapted_games_library_categorization_2',
            field=models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('expr', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('expé', 'expérimentation'), ('fab', 'fabrication')], max_length=10),
        ),
    ]
