# Generated by Django 6.0 on 2025-12-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Number')),
                ('qrcode', models.ImageField(blank=True, upload_to='medias/qrcode')),
                ('state', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=30)),
                ('token', models.PositiveIntegerField()),
                ('to_sold', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.location')),
            ],
        ),
    ]
