# Generated by Django 6.0 on 2025-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
