# Generated by Django 6.0 on 2025-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_details_alter_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('gameboard', 'jds'), ('rpg', 'jdr'), ('wooden', 'bois'), ('toys', 'jouet')], default='gameboard', max_length=20),
        ),
    ]
