# Generated by Django 6.0 on 2025-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('boardgame', 'jds'), ('rpg', 'jdr'), ('wooden', 'bois'), ('toys', 'jouet')], default='boardgame', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
