# Generated by Django 6.0 on 2026-01-16 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='to_sold',
        ),
        migrations.AddField(
            model_name='game',
            name='adapted_games_library_categorization',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='cards_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='cards_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='games_library_categorization',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='last_inventory_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='origin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='players_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rules_video_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='trictrac_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='authors',
            field=models.ManyToManyField(to='games.author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='illustrators',
            field=models.ManyToManyField(to='games.illustrator'),
        ),
        migrations.AddField(
            model_name='game',
            name='labels',
            field=models.ManyToManyField(to='games.label'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanisms',
            field=models.ManyToManyField(to='games.mechanism'),
        ),
    ]
