# Generated by Django 6.0 on 2026-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_author_illustrator_label_mechanism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='toto'),
            preserve_default=False,
        ),
    ]
