# Generated by Django 6.0 on 2026-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='add_date',
            field=models.DateTimeField(null=True, verbose_name='date added'),
        ),
    ]
