# Generated by Django 6.0 on 2026-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
    ]
