# Generated by Django 6.0 on 2026-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_inventory_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last inventory date'),
        ),
    ]
