# Generated by Django 6.0 on 2026-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_last_inventory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='authors',
            field=models.ManyToManyField(blank=True, to='games.author'),
        ),
        migrations.AlterField(
            model_name='game',
            name='illustrators',
            field=models.ManyToManyField(blank=True, to='games.illustrator'),
        ),
        migrations.AlterField(
            model_name='game',
            name='labels',
            field=models.ManyToManyField(blank=True, to='games.label'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, to='games.mechanism'),
        ),
    ]
