# Generated by Django 6.0 on 2026-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_authors_alter_game_illustrators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='myludo_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='add_date',
            field=models.DateField(blank=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_inventory_date',
            field=models.DateField(blank=True, null=True, verbose_name='last inventory date'),
        ),
    ]
