# Generated by Django 6.0 on 2026-01-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_myludo_link_alter_game_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='origin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
