# Generated by Django 6.0 on 2026-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_game_origin_alter_game_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='myludo_link',
            new_name='myludo_path',
        ),
        migrations.RemoveField(
            model_name='game',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trictrac_link',
        ),
        migrations.AddField(
            model_name='game',
            name='editors',
            field=models.ManyToManyField(blank=True, to='games.editor'),
        ),
    ]
