# Generated by Django 6.0 on 2026-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_editor_rename_myludo_link_game_myludo_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='adapted_games_library_categorization',
            new_name='adapted_games_library_categorization_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.RemoveField(
            model_name='game',
            name='token',
        ),
        migrations.AddField(
            model_name='game',
            name='adapted_games_library_categorization_2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='entry_year',
            field=models.PositiveIntegerField(default=1989),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='for_child',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='inventory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='missing_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cards_size',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='game',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules_video_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
