# Generated by Django 6.0 on 2026-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_rename_adapted_games_library_categorization_game_adapted_games_library_categorization_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='games_library_categorization',
            field=models.CharField(blank=True, choices=[('R', 'Règles'), ('E', 'Exercice'), ('S', 'Symbolique'), ('A', 'Assemblage')], max_length=1),
        ),
    ]
