# Generated by Django 6.0 on 2026-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_games_library_categorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='adapted_games_library_categorization_1',
            field=models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('exp', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('exp', 'expérimentation'), ('fab', 'fabrication')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='adapted_games_library_categorization_2',
            field=models.CharField(blank=True, choices=[('sen', 'sensoriel'), ('mot', 'motricité'), ('man', 'manipulation'), ('rôl', 'rôles'), ('mis', 'mise en scène'), ('rep', 'représentation'), ('ass', 'association'), ('par', 'parcours'), ('exp', 'expression'), ('com', 'combinaison'), ('adr', 'adresse'), ('ref', 'réflexion'), ('has', 'hasard'), ('que', 'questions-réponses'), ('cos', 'construction'), ('age', 'agencement'), ('exp', 'expérimentation'), ('fab', 'fabrication')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='games_library_categorization',
            field=models.CharField(blank=True, choices=[('', ''), ('R', 'Règles'), ('E', 'Exercice'), ('S', 'Symbolique'), ('A', 'Assemblage')], max_length=1),
        ),
    ]
