# Generated by Django 6.0 on 2026-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_adapted_games_library_categorization_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='for_child',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False),
        ),
    ]
