# Generated by Django 6.0 on 2026-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='theme',
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, to='games.theme'),
        ),
    ]
